
# .github/workflows/on-pr-merged.yml
name: Run on PR merged to master

on:
  # Manual run
  workflow_dispatch:

  # External POST-trigger
  repository_dispatch:
    types: [externally-triggered-job]

  # Pushes to master (or main)
  push:
    branches:
      - main   # change to "master" if needed

  # Trigger after the merge workflow completes
  workflow_run:
    workflows: ["Auto_PR_for_manifests_branches"]
    types:
      - completed

jobs:
  build:
    # Conditions:
    # - run for push/dispatch
    # - run for workflow_run only if success
    if: >
      github.event_name != 'workflow_run' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test push
        run: |
          echo "PR was merged into master."
          git push origin HEAD:test_trigger
